### PR TITLE
Add script to pin CIDs from pin list

### PR DESCRIPTION
**Pull request by lkluft**
Add a convenience script to pin CIDs from a pin list to the local node and copy them to the MFS. In addition, it is possible to filter for tags.

### CODE REVIEW

**Review by d70-t — APPROVED** [review]
I'm not super sure, if adding all of them by name to the MFS is what we want in all cases, but I see it could be useful for now.

Names can be ambiguous, in that case, just one (more or less undefined) entry would end up in MFS.
And I expect, that we'll end up having a bunch of similar names (e.g. dropsondes v1 ... dropsondes v101) in the pinlist, as every published change will be a new entry in the pinlist. We kind of want to keep old ones in the pinlist, in order not to break existing links, but there's probably not much of a point enumerating all of them in a folder.

Anyways, I guess this is for now a quite helpful tool, so we should merge.

**Comment by lkluft** [comment]
I am also fine with splitting into two scripts or at least two subcommands

**Comment by d70-t** [comment]
Yes, maybe it should be two separate subcommands. Pinning ist kind of like "git fetch" and in a way adding things to MFS ist more comparable to something like "git checkout". Both do quite different things.

I'd probably also remove the name on a pin if there's no name in the Pinlist. I guess having the CID as a name would be more annoying than helpful.
For the MFS entry, one needs a name of course, so in that case, falling back to the CID seems to be a good option.

**Comment by lkluft** [comment]
I have removed the `files cp` part from the script. I will add a helper function in a separate PR.

The PR as is, merely implements the basic `pin add` functionality to work with the `pinlist.yaml`.

**Review by d70-t — APPROVED** [review]

**Pull request merged**
